version: '3.8'
services:
  db:
    image: postgres:16
    container_name: mentalos_postgres
    environment:
      POSTGRES_USER: mentalos
      POSTGRES_PASSWORD: mentalos_password
      POSTGRES_DB: mentalos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: